# Base configs
baseurl: "https://fahadalotaibi.ga"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-75349920-2"

# UI configs
title: "Photography by Fahad Alotaibi"
subtitle: "See the world through my eyes!"
author: "Fahad Alotaibi"
header:
 title: "Photography"
 subtitle: "by Fahad Alotaibi"
footer:
 name: "Hey there, my name is Fahad"
 bio: "I am a developer and a tech aficionado from Saudi Arabia. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/FahadAlo4661"
  twitter: "https://www.twitter.com/pj_fahad"
  instagram: "https://www.instagram.com/fahad.pj"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/in/"
  github: "https://www.github.com/"
